# Generated by Django 5.1.1 on 2024-10-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_account_acc_sponsor_id_account_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAccounts',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.account',),
        ),
    ]
