# Generated by Django 4.2.11 on 2024-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=255)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('ACCOUNT_TYPE', models.CharField(max_length=50)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
