# Generated by Django 4.2.11 on 2024-10-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_login',
            new_name='LAST_LOGIN',
        ),
    ]
