# Generated by Django 4.2.11 on 2024-10-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_last_login_account_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
