# Generated by Django 4.2.11 on 2024-10-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_failed_attempts_account_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
    ]
