# Generated by Django 4.2.11 on 2024-10-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_failed_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='lockout_until',
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
