DROP TABLE IF EXISTS POINT_HISTORY;

DROP TABLE IF EXISTS ACCOUNT_SPONSOR;

DROP TABLE IF EXISTS AUDIT;

DROP TABLE IF EXISTS APPLICATIONS;

DROP TABLE IF EXISTS CATALOG;

DROP TABLE IF EXISTS ACCOUNTS;

DROP TABLE IF EXISTS SPONSORS;
