# Generated by Django 5.1.1 on 2024-10-06 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('SPONSOR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PT_VALUE', models.FloatField()),
                ('DESCRIPTION', models.CharField(max_length=255)),
                ('CREATION_DATE', models.DateTimeField()),
            ],
            options={
                'db_table': 'SPONSORS',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('ACCOUNT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=255)),
                ('ADDRESS', models.CharField(max_length=255)),
                ('CREATION_DATE', models.DateTimeField()),
                ('LAST_LOGIN', models.DateTimeField()),
                ('NUM_POINTS', models.IntegerField()),
                ('BIRTHDAY', models.DateField()),
                ('USERNAME', models.CharField(max_length=255)),
                ('EMAIL', models.CharField(max_length=255)),
                ('BIO', models.CharField(max_length=255)),
                ('ACC_SPONSOR_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.sponsor')),
            ],
            options={
                'db_table': 'ACCOUNTS',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TOKEN', models.CharField(max_length=255)),
                ('CREATED_AT', models.DateTimeField()),
                ('EXPIRES_AT', models.DateTimeField()),
                ('IS_USED', models.BooleanField(default=False)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
            ],
            options={
                'db_table': 'TOKEN',
            },
        ),
    ]
