# Generated by Django 5.1.1 on 2024-10-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_acc_sponsor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='PASSWORD',
            field=models.CharField(default='123', max_length=255),
        ),
    ]
