# Generated by Django 5.1.1 on 2024-10-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='PASSWORD',
            field=models.CharField(max_length=255),
        ),
    ]
