# Generated by Django 5.1.1 on 2024-10-08 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_account_password'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ACC_SPONSOR_ID',
            field=models.ForeignKey(db_column='ACC_SPONSOR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsors.sponsors'),
        ),
        migrations.AddField(
            model_name='account',
            name='ACCOUNT_TYPE',
            field=models.CharField(choices=[('driver', 'Driver'), ('sponsor', 'Sponsor'), ('admin', 'Admin')], default='Driver', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
