# Generated by Django 4.2.11 on 2024-10-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_account_acc_sponsor_id_account_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='STATUS',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=10),
            preserve_default=False,
        ),
    ]
