# Generated by Django 4.2.11 on 2024-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
