# Generated by Django 4.2.11 on 2024-10-29 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
        ('authentication', '0009_remove_account_acc_sponsor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_sponsor',
            name='ACCOUNT_ID',
            field=models.ForeignKey(db_column='ACCOUNT_ID', on_delete=django.db.models.deletion.CASCADE, to='authentication.account'),
        ),
        migrations.AlterField(
            model_name='account_sponsor',
            name='SPONSOR_ID',
            field=models.ForeignKey(db_column='SPONSOR_ID', on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsors'),
        ),
    ]
