# Generated by Django 4.2.11 on 2024-11-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_account_sponsor_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_sponsor',
            name='APP_DATE',
        ),
        migrations.AddField(
            model_name='account_sponsor',
            name='STATUS',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='OPEN', max_length=10),
            preserve_default=False,
        ),
    ]
