# Generated by Django 4.2.11 on 2024-11-04 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_account_sponsor_app_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_sponsor',
            name='APP_DATE',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
