# Generated by Django 4.2.11 on 2024-11-16 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_error_enabled', models.BooleanField(default=False)),
                ('order_placed_enabled', models.BooleanField(default=False)),
                ('points_added_enabled', models.BooleanField(default=False)),
                ('ACCOUNT_ID', models.CharField(max_length=255, unique=True)),
                ('ORDER_ERROR_NOTI', models.BooleanField(default=False)),
                ('ORDER_PLACED_NOTI', models.BooleanField(default=False)),
                ('POINTS_ADDED_NOTI', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
