# Generated by Django 4.2.11 on 2024-11-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='ACCOUNT_ID',
            new_name='username',
        ),
    ]
