# Generated by Django 4.2.11 on 2024-11-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_account_id_notificationpreference_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='ORDER_ERROR_NOTI',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='ORDER_PLACED_NOTI',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='POINTS_ADDED_NOTI',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='username',
        ),
    ]
