# Generated by Django 5.1.1 on 2024-10-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='team_num',
            new_name='ABOUT_ID',
        ),
        migrations.RemoveField(
            model_name='about',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='about',
            name='version_num',
        ),
        migrations.AddField(
            model_name='about',
            name='ABOUT_DESC',
            field=models.CharField(default='PandaSoft is a webapp that tracks truckers and rewards them for good driving', max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='TEAM_NUM',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='about',
            name='PRODUCT_NAME',
            field=models.CharField(default='PandaSoft', max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='RELEASE_DATE',
            field=models.DateTimeField(default='2024-09-24 00:00:00'),
        ),
        migrations.AddField(
            model_name='about',
            name='VERSION_NUM',
            field=models.FloatField(default=1),
        ),
    ]
