# Generated by Django 5.1.1 on 2024-10-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_team_num_about_about_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='ABOUT_DESC',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='PRODUCT_NAME',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='RELEASE_DATE',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='TEAM_NUM',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='VERSION_NUM',
            field=models.FloatField(),
        ),
    ]
