# Generated by Django 5.1.1 on 2024-10-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_about_desc_alter_about_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='id',
        ),
        migrations.AlterField(
            model_name='about',
            name='ABOUT_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
