# Generated by Django 4.2.11 on 2024-10-22 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_account_acc_sponsor_id_account_account_type_and_more'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('EVENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('EVENT_TYPE', models.CharField(max_length=255)),
                ('DESCRIPTION', models.CharField(max_length=255)),
                ('AUDIT_ACCOUNT_ID', models.ForeignKey(db_column='AUDIT_ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account')),
                ('AUDIT_SPONSOR_ID', models.ForeignKey(db_column='AUDIT_SPONSOR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsors.sponsors')),
            ],
            options={
                'db_table': 'AUDIT',
            },
        ),
    ]
