# Generated by Django 4.2.11 on 2024-10-22 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='AUDIT_DATE',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
