# Generated by Django 4.2.11 on 2024-10-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_audit_audit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='AUDIT_DATE',
            new_name='EVENT_TIME',
        ),
    ]
