# Generated by Django 4.2.11 on 2024-10-21 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_account_acc_sponsor_id_account_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('HISTORY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('POINT_CHANGE', models.IntegerField()),
                ('POINT_CHANGE_DATE', models.DateTimeField(default=datetime.datetime.now)),
                ('ITEM_ID', models.IntegerField(null=True)),
                ('REASON', models.CharField(max_length=255, null=True)),
                ('HIST_ACCOUNT_ID', models.ForeignKey(db_column='ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account')),
            ],
            options={
                'db_table': 'POINT_HISTORY',
            },
        ),
    ]
