# Generated by Django 4.2.11 on 2024-10-22 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_account_acc_sponsor_id_account_account_type_and_more'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='SOURCE',
            field=models.CharField(choices=[('ORDER', 'Order'), ('SPONSOR', 'Sponsor')], default='SPONSOR', max_length=255),
        ),
        migrations.AddField(
            model_name='points',
            name='STATUS',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='IN_PROGRESS', max_length=255),
        ),
        migrations.AlterField(
            model_name='points',
            name='HIST_ACCOUNT_ID',
            field=models.ForeignKey(db_column='HIST_ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account'),
        ),
    ]
