# Generated by Django 4.2.11 on 2024-11-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_account_sponsor_app_date'),
        ('points', '0003_points_sponsor_user_id_alter_points_hist_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='HIST_ACCOUNT_ID',
        ),
        migrations.AddField(
            model_name='points',
            name='ACC_SPONSOR_ID',
            field=models.ForeignKey(db_column='ACC_SPONSOR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_history', to='authentication.account_sponsor'),
        ),
    ]
