# Generated by Django 4.2.11 on 2024-11-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_account_sponsor_app_date'),
        ('points', '0005_rename_acc_sponsor_id_points_hist_acc_sponsor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='HIST_ACC_SPONSOR_ID',
            field=models.ForeignKey(db_column='HIST_ACC_SPONSOR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_history', to='authentication.account_sponsor'),
        ),
    ]
